### ISSUE TITLE
Add the Challenges Chunk

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#124]

**Comment by AndyComan** [comment]
https://github.com/fluidtrends/chunky/pull/37

**Comment by AndyComan** [comment]
https://github.com/fluidtrends/chunky/pull/37

https://github.com/fluidtrends/carmel/pull/130

**Comment by AndyComan** [comment]
https://github.com/fluidtrends/carmel/pull/130

**Comment by AndyComan** [comment]
https://github.com/fluidtrends/chunky/pull/37

**Comment by AndyComan** [comment]
https://github.com/fluidtrends/chunky/pull/37

https://github.com/fluidtrends/carmel/pull/130
