### ISSUE TITLE
Carmel in Legger Nano S

### ISSUE THREAD

**Issue by snoopytrader** [fluidtrends/carmel#151]
I have my EOS tokens in Legger nano S. I claim my tokens but i don´t have any EOS em Metamask🙄... I do What a can do now to get my 100 tokens ????

**Comment by AndreiLaz** [comment]
You can transfer 1 EOS from your Legger Nano to the ETH address that you have in Metamask.
Without the presence of EOS token on the ETH address that you have in Metamask, you cannot claim the 100 Carmel Tokens.

**Comment by snoopytrader** [comment]
Thanks for replay. 
But i already try to get my carmel tokens before. If i transfer one EOS token to my metamask  i can claim again. I have this messagem in my claim token page...
Congratulations!
You successfully claimed your FREE Carmel Tokens.

**Comment by snoopytrader** [comment]
I again. I send 1EOS token but 0 Carmel balance :(

**Comment by AndreiLaz** [comment]
The Carmel Tokens are displayed on the web application, when you log in to your account. If you can't see the tokens on web, please reopen the issue.
