### ISSUE TITLE
Complete Claim Validation process

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#169]
- Make sure that Carmel Members who reserved their tokens as part of a claim period, have completed the Social Media (Step 2) of the claiming process.

- [x] Check Telegram
- [x] Check Twitter
- [ ] Check YouTube
- [ ] Check Facebook
- [ ] Check Medium
- [ ] Check Github
- [ ] Check Linkedin
- [ ] Check Instagram
- [ ] Check Steemit

**Comment by mms1365** [comment]
Good project..

**Comment by jinyungyou** [comment]
good eos project!!

**Comment by msp326** [comment]
Good project..

**Comment by hisleh** [comment]
good

**Comment by crisppoker** [comment]
i did all those ty for the airdrop

**Comment by Eazybrah** [comment]
Thanks guyz, appreciate your efforts

**Comment by Eazybrah** [comment]
Yes and thanks

**Comment by yonghyunbeak** [comment]
thanks

**Comment by shawnlauzon** [comment]
Hey @idancali, I would love to use this in our own project at Volentix, 1) would that be possible, and 2) when do you think you'll have it complete? Would be happy to collaborate too!

**Comment by coin536** [comment]
Great!!

**Comment by coin536** [comment]
Good

**Comment by ggasami** [comment]
Good project..

**Comment by coin536** [comment]
Good

**Comment by gang9694** [comment]
good~~~

**Comment by aclowwwn** [comment]
Hey everybody, thank you for the amazing support! Together we can make this project even greater than it already is. You guys are great!

**Comment by aclowwwn** [comment]
Hey, @shawnlauzon, we would love to talk more about that. You can contact Dan at dan@fluidtrends.com. Keep up the good work!

**Comment by lds2890** [comment]
goog!!

**Comment by xzxie** [comment]
Good project

**Comment by gang9694** [comment]
Good project

**Comment by leeup73** [comment]
good!!

**Comment by ekentrix** [comment]
Great project guys.

**Comment by paceromano** [comment]
Good project

**Comment by kbw1140** [comment]
Its nice project

**Comment by ammirevole** [comment]
nice project really...

**Comment by neohuang14** [comment]
Its nice project...

**Comment by harukikitahara1984** [comment]
Validation Pending  till now

**Comment by wjh281** [comment]
good

**Comment by paceromano** [comment]
good

**Comment by preebz21** [comment]
how long does it take pending verification?

**Comment by kbw1140** [comment]
Nice Project.

**Comment by ya0505** [comment]
good!!

**Comment by khwan75** [comment]
good project

**Comment by murzik98** [comment]
Your project has great prospects for development! Good luck!

**Comment by amec3** [comment]
I hope I duly get my tokens

**Comment by s-coast** [comment]
Great progekt

**Comment by FedericoFauu** [comment]
Good Project !! amazing !!

**Comment by acefw** [comment]
good project!

**Comment by ViktorFidanov** [comment]
Good project

**Comment by nintrentr** [comment]
that's nice!

**Comment by StormboyStorm** [comment]
looking forward to it

**Comment by nintrentr** [comment]
GOOD!!

**Comment by maxocoin** [comment]
I followed the project in twitter and telegram and it says "Invalid user name" even when I clock on it it opens twitter and it says "Following".
Is there a special format?  For twitter I tried both  maxocoin and @maxocoin with the same result
