### ISSUE TITLE
Email validation failures

### ISSUE THREAD

**Issue by PaulAttridge** [fluidtrends/carmel#179]
Hi, I have registered and secured tokens but have to receive a validation email as part of the process to continue. I have never received a validation email despite numerous attempts including logging out and logging back in. They have not gone into my spam folder and l have even looked at my service providers quarantine folder and not there either. I then though l would change the email address to another one l use to see if that solved the issue. It seems once you are in transit in the registration verification process you cannot change your email or password? Looking at the thread in Telegram it seems others are not receiving the verification mail either so at least providing the option to change email address may help solve whatever the bug may be for a number of people. I appreciate there is a security element to this so clearly you cannot send an email confirmation potentially to the current registered address so maybe you add a second level of security such as place of birth, first pet name etc and confirm this via txt to a phone number...either way there are a bunch of people stuck in the verification process with reserved tokens.
Regards
PA

**Comment by neohuang14** [comment]
nice

**Comment by AndreiLaz** [comment]
hi @PaulAttridge thank you for reporting this. 

I've sent the issue to the development team, and will update when we have pin-pointed the problem.

Thanks!

**Comment by aclowwwn** [comment]
The issue came from a few specific mail domains, that were blacklisted by Google
