### ISSUE TITLE
Describe the token distribution model

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#19]
# Overview

There is a total supply of 70,000,000 Carmel Tokens of which 60% are available for distribution, 20% are reserved for founders in a Founders Fund, 10% for partners in a Partners Fund and 10% are used for bounties, rewards, scholarships and incentives in a Fluid Fund. The Carmel Token Distribution of the 60% of tokens starts on February 26, 2018 and ends on August 20, 2018, for a total of 25 weeks. 

The campaign is aimed to raise no more than $30,000,000 USD (hard cap) as a means to fund the development and maintenance of the Carmel Platform for the next 5 years. A minimum amount of $8,000,000 USD (soft cap) is required in order to ensure at least 24 months of development and maintenance. All the funds are used exclusively for Product Development and maintenance.

Undistributed tokens are placed in the Fluid Fund. No tokens are burned and no new tokens are created during the distribution campaign. New tokens will be generated daily at a fixed inflation rate of 5% per year and added to the Fluid Fund, starting on Day 1 of the official launch of the Carmel Platform, after the token distribution period ends. 

**Period 1: February 26 - April 2 (5 weeks) - Private Sale**

A total of 3,500,000 Carmel Tokens (5% of total supply) are sold privately at a discount of 50% or more. Tokens are sold privately on a one-on-one basis. Email inquiries about the private sale can be sent to team@fluidtrends.com during the entire duration of the sale. 

**Period 2: April 2 - May 7 (5 weeks) - EOS AirDrop**

A total of 3,500,000 Carmel Tokens (5% of total supply) are distributed free of charge to the first EOS token holders to claim them. Each EOS token holder can claim 100 free Carmel Tokens. Another 50 Carmel Tokens can be earned as bounty for inviting a friend, for up to 5 friends. The total amount of free Carmel Tokens that can be claimed per EOS token holder is 350, thus making the distribution available to at least 10,000 EOS token holders. A maximum of 100,000 tokens are available per day to ensure a wide distribution. 

Tokens can be claimed at carmel.io on a first come first serve basis. Holders are required to complete a form and provide their Ethereum address in order to prove their EOS token ownership. If they have MetaMask installed, the claim is instant, otherwise, it will have to be manual. Holders are also encouraged to enter their name and email address as optional fields, in order to join the Carmel Priority List and receive early purchasing access during the Public Pre-Sale period.

**Period 3: May 7 - June 11 (5 weeks) - Public Pre-Sale**

A total (hard cap) of 7,000,000 Carmel Tokens (10% of total supply) are sold at a progressive discount from the Public Sale price of $1.00 USD. The discount starts at 50% and decreases 10% progressively every week. The accepted currency is ETH at a fixed price calculated as the ETH equivalent of $1.00 USD on Day 1 of the period. A maximum of 200,000 tokens are available per day to ensure a wide distribution. There is a maximum number of 20,000 tokens per day per contributor.

Tokens can be purchased at carmel.io on a first come first serve basis. Buyers can select a predefined amount of tokens (100, 250, 500, 1000, 5000, 10000, 20000) or enter any amount between 50 and 20,0000. The price in ETH is determined based on the active discount. If they have MetaMask installed, the purchase is instant, otherwise, it will have to be manual. The ETH is sent from the Carmel Ethereum Wallet address (not a smart contract). Buyers are also encouraged to enter their name and email address as optional fields, in order to join the Carmel Priority List and receive early purchasing access during the Public Sale period.

**Period 4: June 11 - August 20 (10 weeks) - Public Sale**

A total (hard cap) of 28,000,000 Carmel Tokens (40% of total supply) are sold as ERC-20 tokens. The accepted currency is ETH at a fixed price. The price is the ETH equivalent of $1.00 USD on Day 1 of the sale. A maximum of 400,000 tokens are available per day to ensure a wide distribution. There is a maximum number of 40,000 tokens per day per contributor. 

Tokens can be purchased at carmel.io on a first come first serve basis. Buyers can select a predefined amount of tokens (100, 250, 500, 1000, 5000, 10000, 20000, 40000) or enter an amount between 50 and 40,000. If they have MetaMask installed, the purchase is instant, otherwise, it will have to be manual. The ETH is sent the the Carmel Ethereum Smart Contract address. Buyers are also encouraged to enter their name and email address as optional fields, in order to join the Carmel Priority List and receive early and privileged access to the Carmel Platform before general availability.

**Comment by jen53** [comment]
Is only MetaMask wallet qualify for the Carmel airdrop? How about MEW? I don't see MEW from carmel.io.

**Comment by jen53** [comment]
where the claim form located from carmel.io? for MEW EOS holders? "Holders are required to complete a form and provide their Ethereum address in order to prove their EOS token ownership"
