### ISSUE TITLE
Add a special button on the challenge page for taking the challenge

### ISSUE THREAD

**Issue by adrienbenoist** [fluidtrends/carmel#198]
On the challenge page, a button to take the challenge should be visible on the page.

**Comment by cristofor-io** [comment]
1. Create a components folder in the challenges chunk.
2. Create the specialbutton.js file that will contain the react component for the button in the components folder.
3. Copy the code from chunks\intro\components\telegram.js to the specialbutton.js file
4. Change the code to render the button.
5. Create the index.js file in the components folder and export the SpecialButton component.
6. On the screen folder, edit the main.dev.js file.
7. Import the new SpecialButton component.
8. Create a method for calling the SpecialButton component.
9. Concatenate the SpecialButton component to the MainChallengesScreen component.
10. Save the main.dev.js file.
