### ISSUE TITLE
Render multiple labels for a challenges

### ISSUE THREAD

**Issue by adrienbenoist** [fluidtrends/carmel#202]
In the challenges page the user should see more than 1 label in the challenge box. Now he can see 1 like "Web" or "DevOps". Then he should see multiple ones.

**Comment by AndreiLaz** [comment]
Let's define the other labels. The one you mentioned is:
- Categories [Web, DevOps, Mobile, Cloud, Linux, etc]
I can think of:
- Programming Language [Javascript, HTML, CSS, Java, etc]
- Difficulty Level [Beginner, Entry, Intermediate, Advanced, Expert]

What else?
