### ISSUE TITLE
Create a structure format to write a challenge

### ISSUE THREAD

**Issue by adrienbenoist** [fluidtrends/carmel#203]
As discussed with @idancali let's come up with a way to create smart tags into the markdown so that the Carmel Studio can render those tags into smart action.

At least we need two types of action :

1. Open Studio (at file)
2. Open Terminal (at directory)

Others (lower priority ):
1. Open browser at link
2. Open stackoverflow issue
3. Firebase console (if logged in)
4. AWS console (if logged in)

Implementation ideas :
- investigate custom HTML tags

**Comment by aclowwwn** [comment]
@AndreiLaz this is a duplicated issue, see [here](https://github.com/fluidtrends/carmel/issues/397)
