### ISSUE TITLE
Create alpha challenge prototype validation

### ISSUE THREAD

**Issue by adrienbenoist** [fluidtrends/carmel#204]
From inside the studio we will need to test each challenge's step.
To test a step the studio will run a script (written by the challenge author) and this script has to be written in open source framework. We call this the Carmel Validation Framework.

Implementation ideas :
- investigate Savor
- investigate Cypress
- investigate Jest (if necessary)

Look how Chunky uses Savor for UT.

**Comment by AndreiLaz** [comment]
Good job @poprobertdaniel !

**Comment by poprobertdaniel** [comment]
It's a good job after it's done :D
