### ISSUE TITLE
first attempt at Challenge wasn't saving

### ISSUE THREAD

**Issue by vparashar** [fluidtrends/carmel#265]
steps
-----
installed carmel
went through the welcome process
started my first challenge (to change the menu title to something other than 'Welcome')
I clicked on 'mark challenge complete' button
also pressed 'command + s' save and i saw the message 'Saved' suggesting my changes were saved

what happened?
-------
kept saying that i had not completed, even though i had made the changes as expected. created some confusion if i was doing it in the right place. eventually i stopped the challenge, and restarted it again. this time it worked perfectly.

**Comment by AndreiLaz** [comment]
Thank you for reporting this behavior. This bug is being fixed and will be launched in the next version of the Carmel Studio.
