### ISSUE TITLE
screen gone 'blank' trying to go back to Challenge (just finished)

### ISSUE THREAD

**Issue by vparashar** [fluidtrends/carmel#266]
steps
-----
i completed my first challenge
went back to the screen showing challenges
i remember going back and forth a couple times between opening a completed challenge and challenge list screen
after a couple times doing that

what happens?
--------
the screen has gone blank (completely white) and I can't access the app at all. i'll have to shut it down and start it up again

screenshot attached here;
<img width="1421" alt="screen shot 2018-09-21 at 7 19 45 pm" src="https://user-images.githubusercontent.com/1325118/45909978-6bda0700-bdd3-11e8-888f-b2bf18052d67.png">

**Comment by AndreiLaz** [comment]
Thanks for trying it out. We're on it.
