### ISSUE TITLE
Change cover of site with a animated/inspirational photo

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#267]

**Comment by poprobertdaniel** [comment]
https://www.shutterstock.com/video/clip-32743873-machine-learning-artificial-intelligence-ai-development-concept
https://www.shutterstock.com/video/clip-33435829-blue-hexadecimal-big-data-digital-code-futuristic

**Comment by poprobertdaniel** [comment]
https://www.shutterstock.com/video/clip-32413318-global-network-connected

**Comment by AndreiLaz** [comment]
> https://www.shutterstock.com/video/clip-32743873-machine-learning-artificial-intelligence-ai-development-concept
> https://www.shutterstock.com/video/clip-33435829-blue-hexadecimal-big-data-digital-code-futuristic

the big data digital code futuristic

**Comment by AndreiLaz** [comment]
https://squarefish.eu/

**Comment by AndreiLaz** [comment]
https://thisislandscape.com/

**Comment by AndreiLaz** [comment]
https://www.mazumamobile.com/meet-mazuma/

**Comment by AndreiLaz** [comment]
https://digitalhorizon.vc/

**Comment by AndreiLaz** [comment]
https://algo.tv/

**Comment by AndreiLaz** [comment]
https://cargothefilm2017.com/

**Comment by AndreiLaz** [comment]
http://maxxhat.com/

**Comment by AndreiLaz** [comment]
https://veritystudios.com/

**Comment by AndreiLaz** [comment]
https://www.baraja.com/

**Comment by AndreiLaz** [comment]
https://www.found-studio.com/

**Comment by AndreiLaz** [comment]
http://getcamille.com/

**Comment by AndreiLaz** [comment]
https://technopeak.com/

**Comment by AndreiLaz** [comment]
http://www.levitpen.com/en/
