### ISSUE TITLE
Even though I am signed out, the Studio still remembers that I've finished the challenge

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#285]
When logged out, the Studio should display the challenge as not started or done.

![image](https://user-images.githubusercontent.com/13683260/48939036-ab2feb80-ef1b-11e8-8516-7efecaa4ed2a.png)

**Comment by aclowwwn** [comment]
https://github.com/fluidtrends/carmel/commit/e57d86ac394051379536d695f4ac2d53ac147e1e
