### ISSUE TITLE
EOS Testnet

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#332]

**Comment by idancali** [comment]
deployed locally
deployed on jungletestnet

1. go to https://jungletestnet.io/
2. get an account: https://monitor.jungletestnet.io/#account
3. get some EOS: http://monitor.jungletestnet.io/#faucet
4. add this account to your scatter - use any api endpoint: https://monitor.jungletestnet.io/#apiendpoints
5. add the CARMEL token to your scatter
6. send some EOS to the **carmeltester** account on jungle
7. now you should refresh your scatter and you should see that you received some CARMEL back

the rate for now in this contract is 1:50
