### ISSUE TITLE
Cannot install chunky-cli

### ISSUE THREAD

**Issue by MatthiasBendel** [fluidtrends/carmel#411]
When I try to run 'npm i -g chunky-cli' on Ubuntu18.04, I get the following error:

`sudo -H npm i -g chunky-cli
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
/usr/local/bin/chunky -> /usr/local/lib/node_modules/chunky-cli/bin/cli.js

> node-expat@2.3.17 install /usr/local/lib/node_modules/chunky-cli/node_modules/node-expat
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/chunky-cli/node_modules/node-expat/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/chunky-cli/node_modules/node-expat/.node-gyp'
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/chunky-cli/node_modules/node-expat
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chunky-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-10T11_43_40_006Z-debug.log`

Any ideas what could be the reason?

**Comment by idancali** [comment]
So it's definitely related to file permissions.

> EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.10.0"

and

> EACCES: permission denied, mkdir '/usr/local/lib/node_modules/chunky-cli/node_modules/node-expat/.node-gyp'

And ideally you should never use **sudo** to install global npm modules.

Question for you. How did you install node exactly?

**Comment by MatthiasBendel** [comment]
I followed the instructions on https://github.com/nodejs/help/wiki/Installation with node-v11.10.0-linux-x64.tar.xz but I got a different version output:

`user@pc:~$ /usr/local/lib/nodejs/node-v11.10.0-linux-x64/bin/node -v`
`v11.10.0`
`user@pc:~$ /usr/local/lib/nodejs/node-v11.10.0-linux-x64/bin/npm version`
{ npm: '6.7.0',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }
`user@pc:~$ /usr/local/lib/nodejs/node-v11.10.0-linux-x64/bin/npx -v`
`6.7.0`


When I run `npm i -g chunky-cli` I got:
`Unhandled rejection Error: EACCES: permission denied, open '/home/user/.npm/_cacache/index-v5/d4/86/516fb7c766c1c8c9233114b5792b1031b13a344d3c2bb7e66d44527344fe'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-02-15T11_48_35_726Z-debug.log`

`sudo -H npm i -g chunky-cli` still leads to the error above.

After this I tried to remove node, npm and npx from /usr/local/bin/ and install it with `sudo apt install nodejs`, but this gave me the same error output. By the way, I'm using Ubuntu18.04.

Is there a better way to install node?

After running 
`sudo chown -R $USER:$GROUP ~/.npm`
`sudo chown -R $USER:$GROUP ~/.config`
and then `sudo chown -R user /usr/local/lib/node_modules`
the installation of chunky-cli worked for me!

Thanks for your help!
