### ISSUE TITLE
Restarting a paused challenge takes you to the beginning of the current task

### ISSUE THREAD

**Issue by cristofor-dev** [fluidtrends/carmel#420]
Restating the paused challenge **Change website images** takes to to the beginning of the current task, not the step where you paused the task.

1. Pause the task:
![task1](https://user-images.githubusercontent.com/26462236/52779209-5c907a00-3050-11e9-9d81-c3775b63b9e3.png)

2. The task is paused
![task1a](https://user-images.githubusercontent.com/26462236/52779334-9792ad80-3050-11e9-96f8-447537e3fc7f.png)

3. Restaring the task will take you at the beginning of the task.

![task1b](https://user-images.githubusercontent.com/26462236/52779349-a24d4280-3050-11e9-9eac-2300986a28de.png)

**Comment by idancali** [comment]
What should happen here? Isn't this the desired behaviour? You were at Task 1 and paused the challenge. Then when unpausing, you went back to Task 1. That sounds ok to me.

**Comment by idancali** [comment]
@AndreiLaz @cristofor-dev @aclowwwn @robipop22 thoughts?
