### ISSUE TITLE
The workspace sometimes loads forever

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#431]
When going to the workspace, for some users, it always loads and nothing happens.

**Comment by idancali** [comment]
Looks like this is an issue with users with corrupt data. The case occurs when the user has an active challenge but somehow the db data is corrupt (no tasks). Trying to figure out a solution...

**Comment by idancali** [comment]
The issue was with the fact that the active journey challenge sometimes misses the challenge id. This shouldn't really happen. But if it does we now catch that case by only considering an active journey challenge, one that has an id as well.
