### ISSUE TITLE
Fix Learning Timer

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#432]

**Comment by idancali** [comment]
<img width="707" alt="Screen Shot 2019-08-16 at 10 50 23 PM" src="https://user-images.githubusercontent.com/1070218/63194295-4eabc800-c078-11e9-8ea7-e8e97b6e1d9e.png">

When leaving the task active for a long time - the timer behaves weird

**Comment by idancali** [comment]
- First off, it should calculate the minutes correctly
- And secondly, it should stop everything when the minutes expire
