### ISSUE TITLE
Proof of learning section improvement

### ISSUE THREAD

**Issue by emil622** [fluidtrends/carmel#47]
It's a bit unclear how the proof of learning process is done. In my understanding the downloaded code is like a black box and the user enters his results so he can validate his solution.
If so:
- should he see the challenge provided code after the challenge is successfully completed so he can see the optimal solution if he chosen a different one?
- does the downloaded challenge code actually need to run on the user's device? Most of the times the solution output is just a set of data which is known upfront. So only a match between correct results and user's results is needed, unless the challenge involves some sort of radomness or so.

**Comment by idancali** [comment]
Hi @emil622,

For your first question, the challenge does not have code per say, except for the test. So think for example of a Unit Test. You can write a unit test without writing the code. Maybe you're right, maybe a challenge should also have a sample solution (or a few). I think that's a good idea.

For the second question, the idea is that the code the user writes could be considered sensitive (private) so we don't want that code to leave their machine. And the only way to run a test on it would have to be on that machine. Even if the data to be uploaded is just a match like you said (which will probably be most likely) - running the test itself will have to happen on the machine.

Definitely need to describe a sample scenario for this - in more detail.
