### ISSUE TITLE
Link in whitepaper to document on Token Allocation broken/incorrect?

### ISSUE THREAD

**Issue by vparashar** [fluidtrends/carmel#55]
after reading the whitepaper, I do not have any idea about how the tokens will be allocated or distributed. The link to the detailed doc in 'section: token allocation' led me nowhere of material value.

**Comment by AndreiLaz** [comment]
Hi @vparashar .
The Token distribution model is work in progress, and you can find more at the following ticket:
https://github.com/fluidtrends/carmel/issues/19

Please let us know how do you find the distribution model.

**Comment by idancali** [comment]
The link is deprecated. The Token Distribution Model is now described in the Whitepaper. 

This is related to #19
