### ISSUE TITLE
Use independent experts to evaluate courses instead of using the price set by the author

### ISSUE THREAD

**Issue by tkaraivanov** [fluidtrends/carmel#63]
The price set by the market for courses would not necessarily correlate to their learning value. Some topics would be naturally more expensive than others, and authors could set arbitrary prices or even offer valuable courses for free (which would not be reflected if the learning value is determined by the price).

Therefore, it would be better if the value of each course is determined in a different way. Potentially, this could be done by other established authors in the same subject area.

**Comment by idancali** [comment]
Good one. Related to #64

**Comment by idancali** [comment]
This is covered in #64
