### ISSUE TITLE
What's the main message?

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#76]
Hey all, let's come up with a message that we want to display on the site (and elsewhere) - one that resonates well with our target audience.

**Comment by Btalks** [comment]
"Earn while you Learn!" @idancali

**Comment by idancali** [comment]
Thanks for that, @Btalks - we're actually taking somewhat of a different approach from that model. Our students don't actually "earn" money - they do "earn" experience though. Perhaps we could incorporate that somehow in the message.

**Comment by idancali** [comment]
> Learn How To Build A Better Future For All Of Us
> Grow Your Tech Skills With Programming Challenges And Earn Experience Points

**Comment by idancali** [comment]
We can probably live with this until the next release. Let's keep brainstorming on this for the next one though.

**Comment by idancali** [comment]
We settled on "Redefining Human Work in the Machine Era"
