### ISSUE TITLE
 If a user clicks on "Send Ether", opens Metamask, then closes Metamask, the dasboard remains stuck on the "Just a sec" screen.

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#81]

**Comment by cristianrosu76** [comment]
@AndreiLaz that happened to me as well, and I noticed that Metamask was waiting for my interaction to approve the transaction. Maybe you can add a warning message when the user click the "send" button, telling him that he needs to bring up the Metamask and manually approve the transaction.

**Comment by AndreiLaz** [comment]
@cristianrosu76 do these steps make sense to you? Do they cover the problem raised?

- Go to https://www.carmel.io/
- Sign-in into your account
- Unlock Metamask ( if you don't have the extension added to your browser, please follow the steps found at the following link: https://metamask.io/ )
- Once you have unlocked Metamask, you can select the amount of Carmel Tokens you want to buy either from the horizontal slider, or from +/- signs.
- After you selected the amount of Tokens, you would have to press the "SEND X ETH" button. Then you would have to open Metamask in order to approve the transcation.
- Once the transaction is finished your ammount of Carmel Tokens are updated in your profile.

**Comment by cristianrosu76** [comment]
@AndreiLaz yes, make sense, it's very clear now.

What I would do though is to add the below text in the level-up window.
> Open Metamask in order to approve the transaction<

btw there is a typo : Metamask in order to approve the **transcation**.
