### ISSUE TITLE
Can't login by pressing Enter key (webapp)

### ISSUE THREAD

**Issue by vparashar** [fluidtrends/carmel#96]
chrome (didn't try other browsers)

1. go to carmel.io
2. enter email address and password
3. press 'enter' on keyboard

what happens?
----------------
nothing

what should happen?
-------------------
should be logged into Carmel

**Comment by AndreiLaz** [comment]
hey @vparashar ,

We fixed this issue, adding an activity when pressing the "Enter" keyboard at login. It will be included in the release that we plan for tomorrow.

Stay tuned!
